# Generated by Django 4.1.2 on 2022-11-25 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='', max_length=3)),
                ('name', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='address',
            field=models.TextField(default='-', max_length=200),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cuisineType',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='email',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='timing',
            field=models.CharField(default='-', max_length=80),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='website',
            field=models.CharField(default='-', max_length=40),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurants.city'),
        ),
    ]
