# Generated by Django 4.1.2 on 2022-11-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_city_restaurant_address_restaurant_cuisinetype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='website',
            field=models.CharField(default='-', max_length=300),
        ),
    ]
