# Generated by Django 4.1.2 on 2022-11-25 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_alter_restaurant_email_alter_restaurant_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='aggrating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
