# Generated by Django 4.1.2 on 2022-11-25 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_restaurant_aggrating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='cuisineType',
            new_name='cuisinetype',
        ),
    ]
