# Generated by Django 4.1.2 on 2022-11-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
            ],
        ),
    ]
