# Generated by Django 4.1.2 on 2022-11-24 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_reporter_profile_dob_profile_sex_review_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Reporter',
        ),
    ]
