# Generated by Django 4.1.2 on 2022-11-25 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='price',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=10),
        ),
    ]
