# Generated by Django 4.1.2 on 2022-11-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_hotel_address_hotel_aggrating_hotel_disttocc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='is_free_cancellable',
            field=models.IntegerField(default=1, max_length=1),
        ),
    ]
