# Generated by Django 4.1.2 on 2022-11-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_hotel_is_free_cancellable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='is_free_cancellable',
            field=models.IntegerField(default=1),
        ),
    ]
