# Generated by Django 4.1.2 on 2022-11-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0007_hotel_city_alter_hotel_is_free_cancellable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='imgurl',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
